apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CtiCxam+X1tVDPFy5p1y,iv:Ttyxp2nQK8bIzk5LkbPLayCCC3AUE0wa0p0+Nlo2uBQ=,tag:+Y5380BzHWMOsTspwD9ybg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:bHeEoddinnB1xNz1S7f8ZYVmm2/YoaAgGrafpfE2jnuU94/QXQ==,iv:SoEzIoVTpS59qUzpne+2jsiJsrjWiRoSaUkhv3Z51OU=,tag:C8e8H2SksJgE6mW+Pa8p8g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:tfdyxl+BzdByoOd61scShQ==,iv:wXqqy6b59aFXY1ud9+II754IqRsH9setGVZle3TkSXU=,tag:DOeHU3lPbPJ2yRc3BSZSSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4n24zz47q6xyu7n6xwxaz2u84mhczcqdl0dnhyfakteyl9pvtqedyfze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT1ZBM1ZvQlRxN3djQ2dv
            c0g1OHZSSmd5Zkp0S2N1dXdndVR5ZVN3OTAwCjFvT2drVHhkYVB5ZXZuMCtHc3V5
            bTlJekxJZUd5WjZFbEJweFVaK3cxaFUKLS0tIDJ6OW14NmZiNW84QUZuWGtSNnh0
            Qk5lMGVodi8vcnV4UWhqcmVXand6UjAKj4EtO41MQjKK0D/2A+sxdkQwjxMVUgIJ
            o/43qqdbUdyqQO5zMF76tL4/KjnfE+CZZxyhxWGsEwmMdESkdbOGPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-06T13:31:52Z"
    mac: ENC[AES256_GCM,data:TWI2yoXvPl28bNlzocNIZV8Fi74sjsu5v/U3Ec8lnLiC0S7xepUJ8NJ1oIbEm4eMM4ghogYlLxhpNr2Xy5SM4yEAUbG6787Z4Qe+1hDM04eLjuxphmsBZ0hsqxa95UJ0VUs/sUdas4QB2RhZhR5uJlbC5TNWLAkYUPekO5W7kLg=,iv:9X8qapUMBybV7ZPNQCmgm3pdZdZHgKfRZx1fLsiXadY=,tag:K52ckFZKLAcKnq/aIOpNqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
