---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-base-restic-rest
  namespace: flux-system
spec:
  path: ./kubernetes/base/backup/restic-rest/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: k8up
      namespace: backup
  interval: 30m
  retryInterval: 1m
  timeout: 3m
