apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-hdd
provisioner: cluster.local/local-path-provisioner
parameters:
  nodePath: /mnt/HDD1/k3s-pv-storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
