---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/infra/networking/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-cert-manager
  path: ./kubernetes/infra/networking/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
