apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0sbX1nESeEamQ/68H3hvhNXbv/q1+ZaxIB7CTG1BCxOau9gAfyfdIw==,iv:X9jhhv+AFKkl882AikD1J+x+BbVm/nFIyLOdsDtykkM=,tag:0GGnI8iFHNcLJO5h31Vkjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4n24zz47q6xyu7n6xwxaz2u84mhczcqdl0dnhyfakteyl9pvtqedyfze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFT091MjhnQlVSeTg3VnlU
            OHp2Q0ZmVWI3TXB3WjRFZUlrZ2VqaDAza2lVClVQRTdIL05ZWEFPZVFmMVl0NkZT
            WkdLUWFLNlJjeWdnd3huZ0NxNlVOZGMKLS0tIElVRng5WExKL3Nld1NZT1NTQ21w
            TUdENGxYNVd6VjNLUjJmczI1TExTeEUK7rvKJ5ApE00LWiYFfnSULahaALcYhFHT
            Lk30glo7lYVUISd/NSDkjPEB1NOttH1B1RDagxm8fthLAnV9s6HoTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T20:35:29Z"
    mac: ENC[AES256_GCM,data:1mmIY0rEfktMdSmeevHLEQ8WmF25ISJBrMdNV1E0vpoUowJmPbNdtyTKO7KtcaHXpkZAM3RNj4CoBuFJZ0NALpVHm4FusFBovzjCyLZRUZrvglOPWojDpuh+rblPloamO7Y6PqfR8vMVfEFzId1z2tzOQ9RLmaDcIC6R/fPKVfY=,iv:hndt+/zKrmXamt8Qg7bivwIxSAv31hl7viSnxYHi29s=,tag:pDGbHtmNrcL9C+Q79dercQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
