---
apiVersion: v1
kind: Service
metadata:
  name: finance-backend-service
  namespace: finance
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    matchLabels:
      app: finance-backend
