---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: finance-frontend
  namespace: finance
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: registry.gitlab.com/antoncuranz/financeionic
      tag: dev
    imagePullSecrets:
      - name: gitlab-token
    env:
      - name: BACKEND_URL
        value: https://financeq.${SECRET_DOMAIN}
      - name: KEYCLOAK_CLIENT_ID
        value: finance-frontend
      - name: KEYCLOAK_REALM
        value: home
      - name: KEYCLOAK_URL
        value: https://keycloak.${SECRET_DOMAIN}
    service:
      main:
        ports:
          http:
            port: &port 80
    probes:
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "finance.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1024Mi
