---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/dockerconfigjson
metadata:
  name: gitlab-token
  namespace: finance
spec:
  itemPath: "vaults/Kubernetes/items/Gitlab Registry Access Token"
