---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak3
  namespace: finance
spec:
  interval: 15m
  chart:
    spec:
      chart: keycloak
      version: 15.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    production: true
    global:
      storageClass: local-path
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hostname: "keycloak.${SECRET_DOMAIN}"
      servicePort: https
      tls: true
    tls:
      enabled: true
