---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finance
resources:
  - ./postgres-helmrelease.yaml
  - ./backend-helmrelease.yaml
  - ./frontend-helmrelease.yaml
  - ./gitlab-token.yaml
  - ./secret.yaml
