---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finance
resources:
  - ./postgres-helmrelease.yaml
  - ./keycloak-helmrelease.yaml
  - ./backend-deployment.yaml
  - ./frontend-deployment.yaml
