---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 12.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      database: finance
      username: postgres
      password: postgres
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "15.2.0"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
