---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./pihole/ks.yaml
  - ./immich/ks.yaml
  - ./homebridge/ks.yaml
  - ./dashboard/ks.yaml
  - ./jellyfin/ks.yaml
