---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-k8s-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-metallb-config
  path: ./kubernetes/infra/networking/k8s-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
