---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword
  namespace: onepassword
spec:
  interval: 15m
  chart:
    spec:
      chart: connect
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    connect:
      serviceType: ClusterIP
      credentialsName: onepassword-secret
      credentialsKey: credentials
    operator:
      create: true
      token:
        name: onepassword-secret
