---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-backup-k8up
  namespace: flux-system
spec:
  path: ./kubernetes/apps/backup/k8up/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: dashboard
      namespace: backup
  interval: 30m
  retryInterval: 1m
  timeout: 3m
