---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: keycloak
      version: 15.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    production: true
    proxy: edge
    global:
      storageClass: local-path
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hostname: "keycloak.${SECRET_DOMAIN}"
    initContainers:
      - name: theme-provider
        image: registry.gitlab.com/antoncuranz/keycloak-theme:latest
        command:
          - sh
        args:
          - -c
          - cp -R /keywind/* /theme
        volumeMounts:
          - name: theme
            mountPath: /theme
    extraVolumeMounts:
      - name: theme
        mountPath: /opt/bitnami/keycloak/themes/keywind
    extraVolumes:
      - name: theme
        emptyDir: {}
