---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  KUBE_VIP_ADDR: "192.168.0.161"
  METALLB_LB_RANGE: "192.168.0.150-192.168.0.160"
  METALLB_K8S_GATEWAY_ADDR: "192.168.0.150"
  METALLB_INGRESS_ADDR: "192.168.0.151"
