---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/linuxserver/sonarr
      tag: version-3.0.10.1567
    env:
      TZ: Europe/Berlin
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 250Mi
        storageClass: local-path
      serien:
        enabled: true
        type: hostPath
        hostPath: /mnt/HDD1/Public/Serien
        mountPath: /serien
    service:
      main:
        ports:
          http:
            port: &port 8989
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /ping
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1024Mi
