---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
type: Opaque
stringData:
  repoPassword: asdf
---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-test
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: backup-secrets
      key: repoPassword
    rest:
      userSecretRef:
        name: backup-secrets
        key: user
      passwordSecretReg:
        name: backup-secrets
        key: password
