---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: haugene/transmission-openvpn
      tag: 5.0.2
    env:
      OPENVPN_PROVIDER: "custom"
      OPENVPN_USERNAME: "user"
      OPENVPN_PASSWORD: "pass"
      LOCAL_NETWORK: "192.168.0.0/16"
      TRANSMISSION_WEB_UI: "combustion"
    persistence:
      data:
        enabled: true
        existingClaim: transmission-data
    service:
      main:
        ports:
          http:
            port: &port 9091
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "transmission.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 1024Mi
      limits:
        memory: 4096Mi
