---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: haugene/transmission-openvpn
      tag: 5.0.2
    env:
      TZ: Europe/Berlin
      LOCAL_NETWORK: 10.42.0.0/16
      OPENVPN_PROVIDER: custom
      OPENVPN_USERNAME: user
      OPENVPN_PASSWORD: pass
      TRANSMISSION_WEB_UI: combustion
    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /srv/Transmission
        mountPath: /data
      openvpn-config:
        enabled: true
        type: secret
        # accessMode: ReadWriteOnce
        # size: 25Mi
        # storageClass: local-path
        mountPath: /etc/openvpn/custom
    service:
      main:
        ports:
          http:
            port: &port 9091
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: &host "transmission.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - NET_ADMIN
      privileged: true
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          exec:
            command: ["ping", "-I", "tun0", "-c", "1", "google.com"]
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
      readiness: *probes
      startup:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 1024Mi
      limits:
        memory: 4096Mi
