apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-data-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: transmission-data
  hostPath:
    path: /srv/Transmission
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: transmission-data
spec:
  storageClassName: manual
  volumeName: transmission-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
