---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      tag: v1.56.2
    immich:
      persistence:
        library:
          existingClaim: immich-data
    postgresql:
      enabled: true
      global:
        storageClass: local-path
    redis:
      enabled: true
      global:
        storageClass: local-path
    typesense:
      enabled: true
      persistence:
        tsdata:
          enabled: true
          storageClass: local-path
    proxy:
      ingress:
        main:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hosts:
            - host: "immich.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
