apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ant0n/immich"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: default
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
