apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: default
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-hdd
  resources:
    requests:
      storage: 1Gi
