---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-ingress-nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-cert-manager-issuers
  path: ./kubernetes/infra/networking/ingress-nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infra-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-infra-ingress-nginx-certificates
    - name: cluster-infra-metallb-config
  path: ./kubernetes/infra/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
